import type { AppState, BusinessProfile } from "@/types";

const beauty: BusinessProfile = {
  id: "beauty",
  ownerName: "Алина Соколова",
  legalForm: "ИП",
  city: "Москва",
  legalStatusLabel: "Действующий",
  industryLabel: "Бьюти",
  products: ["Альфа-Касса", "Приём оплаты с телефона"],
  accountBalance: 128400,
  stabilityFund: 146000,
  stabilityFundHistory: [
    { vendor: "Поставщик расходников «ПрофБьюти»", amount: 18000, date: "2026-05-14" },
    { vendor: "Аренда студии, июнь", amount: 42000, date: "2026-06-01" },
  ],
  trustRating: {
    level: "Активный бизнесмен",
    nextLevel: "Надёжный партнёр",
    progressPercent: 70,
    turnoverNote: "Стабильные обороты по счёту 4 месяца подряд",
    productsConnected: 2,
    productsTotal: 5,
  },
  campaigns: [
    {
      id: "beauty-campaign-1",
      type: "first",
      title: "Кресло и лампа для студии",
      goal: "Обновить рабочее место мастера",
      goalAmount: 45000,
      raisedPercent: 100,
      supportersCount: 3,
      donors: [
        { name: "Мария К.", amount: 2400 },
        { name: "Дмитрий П.", amount: 1800 },
        { name: "Света В.", amount: 3000 },
      ],
      bonuses: ["Скидка 15% на услуги", "Ранний доступ к записи"],
      status: "реализовано",
      createdAt: "2026-04-02",
    },
  ],
  lastTransaction: {
    amount: 2400,
    discountPercent: 15,
    viaProduct: "Альфа-Кассу",
    date: "2026-07-10",
  },
  sandboxResult: { capital: 850000, paybackMonths: 14, risk: "medium", recommendedAmount: 220000 },
  sandboxInputs: {
    niche: "beauty",
    city: "Москва",
    revenue: "450000",
    expenses: "310000",
    avgCheck: "1800",
    clients: "250",
  },
  hasOverdraft: false,
  altCreditUnlocked: false,
};

const horeca: BusinessProfile = {
  id: "horeca",
  ownerName: "Тимур Ахметов",
  legalForm: "Самозанятый",
  city: "Казань",
  legalStatusLabel: "Действующий",
  industryLabel: "HoReCa",
  products: ["Приём оплаты с телефона", "СБП без эквайринга"],
  accountBalance: 64200,
  stabilityFund: 38000,
  stabilityFundHistory: [{ vendor: "Поставщик продуктов «Свежий день»", amount: 9500, date: "2026-06-20" }],
  trustRating: {
    level: "Активный бизнесмен",
    nextLevel: "Надёжный партнёр",
    progressPercent: 40,
    turnoverNote: "Растущие обороты, сезонные колебания по будням",
    productsConnected: 2,
    productsTotal: 5,
  },
  campaigns: [
    {
      id: "horeca-campaign-1",
      type: "first",
      title: "Абонемент на 100 обедов по цене 80",
      goal: "Расширить меню фудтрака",
      goalAmount: 60000,
      raisedPercent: 82,
      supportersCount: 2,
      donors: [
        { name: "Олег С.", amount: 1600 },
        { name: "Карина Р.", amount: 2000 },
      ],
      bonuses: ["Скидка 20% на первый обед", "Промокод на второй абонемент"],
      status: "активна",
      createdAt: "2026-06-05",
    },
  ],
  lastTransaction: {
    amount: 1200,
    discountPercent: 20,
    viaProduct: "СБП/терминал Альфы",
    date: "2026-07-15",
  },
  sandboxResult: { capital: 320000, paybackMonths: 9, risk: "high", recommendedAmount: 90000 },
  sandboxInputs: {
    niche: "horeca",
    city: "Казань",
    revenue: "180000",
    expenses: "140000",
    avgCheck: "450",
    clients: "400",
  },
  hasOverdraft: false,
  altCreditUnlocked: false,
};

const retail: BusinessProfile = {
  id: "retail",
  ownerName: "Настя Волкова",
  legalForm: "ИП",
  city: "Санкт-Петербург",
  legalStatusLabel: "Действующий",
  industryLabel: "Розница",
  products: ["Облачная касса", "Alfa Pay"],
  accountBalance: 212000,
  stabilityFund: 0,
  stabilityFundHistory: [],
  trustRating: {
    level: "Новичок",
    nextLevel: "Активный бизнесмен",
    progressPercent: 15,
    turnoverNote: "Первые обороты после ухода с маркетплейса",
    productsConnected: 2,
    productsTotal: 5,
  },
  campaigns: [
    {
      id: "retail-campaign-1",
      type: "first",
      title: "Тест спроса: предзаказ первой партии худи",
      goal: "Проверить спрос перед производством партии",
      goalAmount: 80000,
      raisedPercent: 130,
      supportersCount: 4,
      donors: [
        { name: "Юля М.", amount: 3500 },
        { name: "Артём Б.", amount: 5000 },
        { name: "Полина Д.", amount: 1500 },
        { name: "Игорь Т.", amount: 2200 },
      ],
      bonuses: ["Скидка 10% на первый заказ", "Худи с промокодом донатера"],
      status: "перевыполнена",
      createdAt: "2026-06-28",
    },
  ],
  lastTransaction: {
    amount: 3500,
    discountPercent: 10,
    viaProduct: "Alfa Pay",
    date: "2026-07-18",
  },
  sandboxResult: { capital: 540000, paybackMonths: 11, risk: "low", recommendedAmount: 150000 },
  sandboxInputs: {
    niche: "retail",
    city: "Санкт-Петербург",
    revenue: "300000",
    expenses: "190000",
    avgCheck: "2600",
    clients: "180",
  },
  hasOverdraft: false,
  altCreditUnlocked: false,
};

export const mockProfiles: Record<BusinessProfile["id"], BusinessProfile> = {
  beauty,
  horeca,
  retail,
};

export const initialAppState: AppState = {
  hasSeenIntro: false,
  hasOpenedAccount: false,
  activeProfileId: "beauty",
  profiles: mockProfiles,
};
